version: '3'
networks: 
  private:
    name: private
  web:
    name: web
  
  
    
services:
  traefik:
    container_name: traefik
#    restart: unless-stopped
    image: traefik:v2.4.2
    ports:
      - 80:80
      - 443:443
    command:
      - --api=true
      - --api.dashboard=true
      
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - --providers.docker.watch=true
      - --providers.docker.network=web
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.dsp4-5archio19-ah-je-gh-yb.fr`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - web
    extra_hosts:
      - "gogs.dsp4-5archio19-ah-je-gh-yb.fr:51.159.28.65"
      - "traefik.dsp4-5archio19-ah-je-gh-yb.fr:51.159.28.65"
      - "jenkins.dsp4-5archio19-ah-je-gh-yb.fr:51.159.28.65"
      - "pma.dsp4-5archio19-ah-je-gh-yb.fr:51.159.28.65"
      - "dsp4-5archio19-ah-je-gh-yb.fr:51.159.28.65"
  gogs-db:
    image: postgres:13-alpine
    container_name: gogs-db
    volumes: 
      - ./data/gogs/postgres:/var/lib/postgresql/data
    networks: 
      - private
    environment: 
      - POSTGRES_DB=gogs
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
    restart: always

    
#---------------------
# gogs
#---------------------  
  gogs:
    image: gogs/gogs:latest
    restart: always
    container_name: gogs
    ports:
      - 2222:2222
    networks: 
      - private
      - web
    volumes:
      - ./data/gogs/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gogs.rule=Host(`gogs.dsp4-5archio19-ah-je-gh-yb.fr`)
      - traefik.http.services.gogs.loadbalancer.server.port=3000


  
# #---------------------
# # mysql database
# #--------------------- 
#   mysql:
#     container_name: mysql
#     image: mysql:latest
#     ports:
#       - 3306:3306 #VM:Containter
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       #MYSQL_DATABASE: ${MYSQL_DATABASE}
#     networks: 
#       - private
#     volumes:
#       - $PWD/sql/sql-backup/:/backup/
#       - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#     command: --character-set-server=utf8 --collation-server=utf8_general_ci


   
# # #---------------------
# # # phpmyadmin
# # #---------------------  
#   phpmyadmin:
#      image: phpmyadmin/phpmyadmin
#      container_name: phpmyadmin
#      depends_on:
#        - mysql
#      environment:
#        MYSQL_USERNAME: ${MYSQL_USERNAME}
#        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#        PMA_HOST: mysql
#      labels:
#        - traefik.enable=true
#        - traefik.http.routers.pma.rule=Host(`pma.dsp4-5archio19-ah-je-gh-yb.fr`)
       
#      networks: 
#       - private
#       - web
      
#---------------------
# jenkins 
#---------------------

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    volumes:
      - ./data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/app
    user: 0:0
    networks: 
      - private
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.dsp4-5archio19-ah-je-gh-yb.fr`)
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

