version: '3.8'
    
services:
#---------------------
# reverse proxy
#---------------------
  reverse-proxy:
    image: nginx
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
 
#---------------------
# jenkins 
#---------------------

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - $PWD:/app
    user: 0:0

#---------------------
# terraform 
#---------------------

  # terraform:
  #   build:
  #     context: .
  #     dockerfile: terraform.Dockerfile
  #   container_name: terraform
  #   networks:
  #     - proxy