global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'scalyr-blog'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['51.159.6.21:9100']
      
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']    
      
  -  job_name: 'jenkins'
     metrics_path: '/prometheus'
     static_configs:
       - targets: ['jenkins:8080']