

certificatesResolvers:
  lets-encr:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: acme.json
      email: bouskilayehouda+acme@gmail.com
      httpChallenge:
        entryPoint: web
